[project]
name = "cs787"
version = "1.0.0"
description = "CS787 Project"
readme = "README.md"
requires-python = "=3.12"
dependencies = [
  "torch>=2.3.0",
  "torchvision>=0.20.0",
  "transformers>=4.44.0",
  "datasets>=2.14.0",
  "einops>=0.7.0",
]

[project.optional-dependencies]
dev = [
  "ruff>=0.5.0",
]
